package log4mex.fox.entity;

import log4mex.fox.token.*;
import org.aksw.mex.log4mex.MEXSerializer;
import org.aksw.mex.log4mex.MyMEX;
import org.aksw.mex.log4mex.algo.AlgorithmVO;
import org.aksw.mex.util.MEXConstant;
import org.aksw.mex.util.MEXEnum.*;

import java.util.Date;

/**
 * Created by esteves on 27.06.15.
 */
public class Dataset1 {

    public static void main(String[] args) {

        System.out.println("starting Fox");

        //the MEX wrapper!
        MyMEX mex = new MyMEX();

        try{

        //basic authoring provenance
        {
            //change later here the sets for adds
            mex.setAuthorName("René Speck");
            mex.setAuthorEmail("speck@informatik.uni-leipzig.de");
            mex.setContext(EnumContexts.RECOMENDER_SYSTEMS);
            mex.setOrganization("Leipzig University");

            mex.setExperimentId("E1_token");
            mex.setExperimentTitle("token-based experiment");
            mex.setExperimentDate(new Date());
            mex.setExperimentDescription("Token-based evaluation on 15 ensemble learning algorithms");
        }

        String eid = "E001C001";
        //ml-experiment-configuration
        {
            mex.addConfiguration(eid);

            mex.Configuration(eid).setDescription("analyzing 10-fold cross validation for 15 algorithms");
            //mex.Configuration(eid).addModel("svm20150322", "model generated by LibSVM", new Date());
            mex.Configuration(eid).addSamplingMethod(EnumSamplingMethods.CROSS_VALIDATION, 10);
            mex.Configuration(eid).SamplingMethod().setTrainSize(0.9);
            mex.Configuration(eid).SamplingMethod().setTestSize(0.1);
            mex.Configuration(eid).SamplingMethod().setSequential(true);

            mex.Configuration(eid).addHardwareConfiguration("ubuntu", EnumProcessors.INTEL_COREI7, EnumRAM.SIZE_16GB, "SSD", EnumCaches.CACHE_3MB);


            mex.Configuration(eid).DataSet().setName("web");
            mex.Configuration(eid).DataSet().setDescription("ataset consists of 20 annotated Web sites");
            mex.Configuration(eid).DataSet().setURI("http://l2r.cs.uiuc.edu/∼cogcomp/software.php");

        }

        //adding algorithms and parameters
        AlgorithmVO alg1,alg2,alg3,alg4,alg5,alg6,alg7,alg8,alg9,alg10,alg11,alg12,alg13,alg14,alg15,alg16,alg17,alg18,alg19;
        {
            //mex.Configuration(eid).addImplementation(EnumImplementations., "3.6.6");

            alg1 = mex.Configuration(eid).addAlgorithm(EnumAlgorithms.BaggingJ48);
            alg2 = mex.Configuration(eid).addAlgorithm(EnumAlgorithms.SequentialMinimalOptimization);
            alg3 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.AdditiveLogisticRegression);
            alg4 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.DecisionTable);
            alg5 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.NaiveBayes);
            alg6 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.SimpleVoting);
            alg7 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.LogisticModelTrees);
            alg8 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.NER_OPEN_NLP);
            alg9 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.MultilayerPerceptron);
            alg10 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.J48);
            alg11 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.NER_STANFORD);
            alg12 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.SupportVectorMachines);
            alg13 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.NER_ILLINOIS_EXTENDED);
            alg14 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.FunctionalTrees);
            alg15 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.AdaBoostM1);
            alg16 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.ClassLevelVoting);
            alg17 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.NER_BALIE);
            alg18 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.RandomForest);
            alg19 =mex.Configuration(eid).addAlgorithm(EnumAlgorithms.LogisticRegression);

            String[] param = {"C", "10^3", "alpha", "0.2"};
            alg1.addParameter(param);
        }
        

        String ex1 = "EX001";
        String ex2 = "EX002";
        String ex3 = "EX003";
        String ex4 = "EX004";
        String ex5 = "EX005";
        String ex6 = "EX006";
        String ex7 = "EX007";
        String ex8 = "EX008";
        String ex9 = "EX009";
        String ex10 = "EX010";
        String ex11 = "EX011";
        String ex12 = "EX012";
        String ex13 = "EX013";
        String ex14 = "EX014";
        String ex15 = "EX015";
        String ex16 = "EX016";
        String ex17 = "EX017";
        String ex18 = "EX018";
        String ex19 = "EX019";
        String ex20 = "EX020";
        String ex21 = "EX021";
        String ex22 = "EX022";
        String ex23 = "EX023";
        String ex24 = "EX024";
        String ex25 = "EX025";
        String ex26 = "EX026";
        String ex27 = "EX027";
        String ex28 = "EX028";
        String ex29 = "EX029";
        String ex30 = "EX030";
        String ex31 = "EX031";
        String ex32 = "EX032";
        String ex33 = "EX033";
        String ex34 = "EX034";
        String ex35 = "EX035";
        String ex36 = "EX036";
        String ex37 = "EX037";
        String ex38 = "EX038";
        String ex39 = "EX039";
        String ex40 = "EX040";
        String ex41 = "EX041";
        String ex42 = "EX042";
        String ex43 = "EX043";
        String ex44 = "EX044";
        String ex45 = "EX045";
        String ex46 = "EX046";
        String ex47 = "EX047";
        String ex48 = "EX048";
        String ex49 = "EX049";
        String ex50 = "EX050";
        String ex51 = "EX051";
        String ex52 = "EX052";
        String ex53 = "EX053";
        String ex54 = "EX054";
        String ex55 = "EX055";
        String ex56 = "EX056";
        String ex57 = "EX057";
        String ex58 = "EX058";
        String ex59 = "EX059";
        String ex60 = "EX060";
        String ex61 = "EX061";
        String ex62 = "EX062";
        String ex63 = "EX063";
        String ex64 = "EX064";
        String ex65 = "EX065";
        String ex66 = "EX066";
        String ex67 = "EX067";
        String ex68 = "EX068";
        String ex69 = "EX069";
        String ex70 = "EX070";
        String ex71 = "EX071";
        String ex72 = "EX072";
        String ex73 = "EX073";
        String ex74 = "EX074";
        String ex75 = "EX075";
        String ex76 = "EX076";
        String ex77 = "EX077";
        
        
        //associate your run x each algorithm
        {
            mex.Configuration(eid).addExecution(EnumExecutionsType.OVERALL, EnumPhases.TEST);
           // mex.Configuration(eid).setExecutionId(0, ex1);

            mex.Configuration(eid).Execution(ex1).setStartDate(new Date());
            mex.Configuration(eid).Execution(ex1).setAlgorithm(mex.Configuration(eid).Algorithm(EnumAlgorithms.BaggingJ48));
            //mex.Configuration(eid).Execution(ex1).setStartsAtPosition("1233");
           // mex.Configuration(eid).Execution(ex1).setEndsAtPosition("1376");
            mex.Configuration(eid).Execution(ex1).addPerformance(EnumMeasures.RECALL, .96);
            mex.Configuration(eid).Execution(ex1).addPerformance(EnumMeasures.PRECISION, .70);
            mex.Configuration(eid).Execution(ex1).addPerformance(EnumMeasures.FMEASURE, .70);
            mex.Configuration(eid).Execution(ex1).addPerformance(EnumMeasures.ERROR, .70);
            mex.Configuration(eid).Execution(ex1).addPerformance(EnumMeasures.MCC_MATTHEWS_COR_COEF, .70);
            mex.Configuration(eid).Execution(ex1).setTargetClass("LOCATION");



                //your models call here !
            mex.Configuration(eid).Execution(ex1).setEndDate(new Date());
        }
        
        
        {
            mex.Configuration(eid).addExecution(EnumExecutionsType.OVERALL, EnumPhases.TEST);
            mex.Configuration(eid).setExecutionId(1, ex2);

            mex.Configuration(eid).Execution(ex2).setStartDate(new Date());
            mex.Configuration(eid).Execution(ex2).setAlgorithm(mex.Configuration(eid).Algorithm(EnumAlgorithms.SupportVectorMachines));
            mex.Configuration(eid).Execution(ex2).setStartsAtPosition("1377");
            mex.Configuration(eid).Execution(ex2).setEndsAtPosition("1420");

                //your models call here !
            mex.Configuration(eid).Execution(ex2).setEndDate(new Date());

            mex.Configuration(eid).Execution(ex2).addPerformance(EnumMeasures.ERROR, .04);
            mex.Configuration(eid).Execution(ex2).addPerformance(EnumMeasures.ACCURACY, .83);
            mex.Configuration(eid).Execution(ex2).addPerformance(EnumMeasures.TRUEPOSITIVERATE, .61);

        //saving performances for each run
        }


            try{
                MEXSerializer.getInstance().saveToDisk("../metafiles/log4mex/fox/ex004", "http://mex.aksw.org/examples/", mex, MEXConstant.EnumRDFFormats.JSON_LD);
            }catch (Exception e){
                System.out.print(e.toString());
            }

            System.out.println("The MEX file [ex004] has been successfully created: share it ;-)");

        System.exit(0);

        }catch (Exception e){
            System.out.println(e.toString());
        }


    }

}
